/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List player balances. */
        get: operations["ListBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List closed-game results. */
        get: operations["ListGameResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List games. */
        get: operations["ListGames"];
        put?: never;
        /** Create a game. */
        post: operations["CreateGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a game. */
        get: operations["GetGame"];
        put?: never;
        post?: never;
        /** Delete an open game. */
        delete: operations["DeleteGame"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/buy-ins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a buy-in to a game. */
        post: operations["AddBuyIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/cash-outs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a cash-out to a game. */
        post: operations["AddCashOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/entries/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a game entry. */
        delete: operations["DeleteGameEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a game. */
        post: operations["CloseGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payments. */
        get: operations["ListPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{playerId}/payments/made": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a payment made by a player. */
        post: operations["RecordPaymentMadeByPlayer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{playerId}/payments/received": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a payment received by a player. */
        post: operations["RecordPaymentReceivedByPlayer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a payment. */
        get: operations["GetPayment"];
        put?: never;
        post?: never;
        /** Delete a payment. */
        delete: operations["DeletePayment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List players. */
        get: operations["ListPlayers"];
        put?: never;
        /** Create a player. */
        post: operations["CreatePlayer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a player. */
        get: operations["GetPlayer"];
        /** Update a player. */
        put: operations["UpdatePlayer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a player. */
        post: operations["ArchivePlayer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddBuyInRequest: {
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
        };
        AddBuyInResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            gameId: string;
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
            type: components["schemas"]["GameEntryType"];
            /** Format: date-time */
            recordedAtUtc: string;
        };
        AddCashOutRequest: {
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
        };
        AddCashOutResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            gameId: string;
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
            type: components["schemas"]["GameEntryType"];
            /** Format: date-time */
            recordedAtUtc: string;
        };
        ArchivePlayerResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            emailAddress: null | string;
            isActive: boolean;
        };
        CloseGameResponse: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["GameStatus"];
            /** Format: date-time */
            createdAtUtc: string;
        };
        CreateGameResponse: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["GameStatus"];
            /** Format: date-time */
            createdAtUtc: string;
        };
        RecordPaymentRequest: {
            /** Format: double */
            amount: number | string;
            method: components["schemas"]["PaymentMethod"];
        };
        RecordPaymentResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
            direction: components["schemas"]["PaymentDirection"];
            method: components["schemas"]["PaymentMethod"];
            /** Format: date-time */
            recordedAtUtc: string;
        };
        CreatePlayerRequest: {
            name: null | string;
            emailAddress: null | string;
        };
        CreatePlayerResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            emailAddress: null | string;
            isActive: boolean;
        };
        ErrorResponse: {
            error: string;
        };
        /** @enum {unknown} */
        GameEntryType: "BuyIn" | "CashOut";
        /** @enum {unknown} */
        GameStatus: "Open" | "Closed";
        GetGameEntryResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
            type: components["schemas"]["GameEntryType"];
            /** Format: date-time */
            recordedAtUtc: string;
        };
        GetGamePlayerTotalResponse: {
            /** Format: uuid */
            playerId: string;
            playerName: string;
            /** Format: double */
            buyInAmount: number | string;
            /** Format: double */
            cashOutAmount: number | string;
            /** Format: double */
            netAmount: number | string;
        };
        GetGameResponse: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["GameStatus"];
            /** Format: date-time */
            createdAtUtc: string;
            /** Format: double */
            totalBuyInAmount: number | string;
            /** Format: double */
            totalCashOutAmount: number | string;
            /** Format: double */
            remainingCashOutAmount: number | string;
            entries: components["schemas"]["GetGameEntryResponse"][];
            playerTotals: components["schemas"]["GetGamePlayerTotalResponse"][];
        };
        GetPaymentResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
            direction: components["schemas"]["PaymentDirection"];
            method: components["schemas"]["PaymentMethod"];
            /** Format: date-time */
            recordedAtUtc: string;
        };
        GetPlayerResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            emailAddress: null | string;
            isActive: boolean;
        };
        ListBalancesResponse: {
            /** Format: uuid */
            playerId: string;
            playerName: string;
            isActive: boolean;
            /** Format: double */
            gameNetAmount: number | string;
            /** Format: double */
            paymentNetAmount: number | string;
            /** Format: double */
            balanceAmount: number | string;
        };
        ListGameResultsResponse: {
            /** Format: uuid */
            playerId: string;
            playerName: string;
            /** Format: uuid */
            gameId: string;
            /** Format: date-time */
            playedAtUtc: string;
            /** Format: double */
            buyInAmount: number | string;
            /** Format: double */
            cashOutAmount: number | string;
            /** Format: double */
            netAmount: number | string;
        };
        ListGamesResponse: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["GameStatus"];
            /** Format: date-time */
            createdAtUtc: string;
        };
        ListPaymentsResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
            direction: components["schemas"]["PaymentDirection"];
            method: components["schemas"]["PaymentMethod"];
            /** Format: date-time */
            recordedAtUtc: string;
        };
        ListPlayersResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            emailAddress: null | string;
            isActive: boolean;
        };
        /** @enum {unknown} */
        PaymentMethod: "ETransfer" | "Cash";
        /** @enum {unknown} */
        PaymentDirection: "MadeByPlayer" | "ReceivedByPlayer";
        UpdatePlayerRequest: {
            name: null | string;
            emailAddress: null | string;
        };
        UpdatePlayerResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            emailAddress: null | string;
            isActive: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListBalances: {
        parameters: {
            query?: {
                playerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBalancesResponse"][];
                };
            };
        };
    };
    ListGameResults: {
        parameters: {
            query?: {
                playerId?: string;
                gameId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListGameResultsResponse"][];
                };
            };
        };
    };
    ListGames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListGamesResponse"][];
                };
            };
        };
    };
    CreateGame: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateGameResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetGameResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeleteGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AddBuyIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddBuyInRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddBuyInResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AddCashOut: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCashOutRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddCashOutResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeleteGameEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: string;
                entryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CloseGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloseGameResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ListPayments: {
        parameters: {
            query?: {
                playerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPaymentsResponse"][];
                };
            };
        };
    };
    RecordPaymentMadeByPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordPaymentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordPaymentResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    RecordPaymentReceivedByPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordPaymentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordPaymentResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPaymentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeletePayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ListPlayers: {
        parameters: {
            query?: {
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPlayersResponse"][];
                };
            };
        };
    };
    CreatePlayer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlayerRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePlayerResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPlayerResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    UpdatePlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlayerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatePlayerResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ArchivePlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchivePlayerResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
