/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List player balances. */
        get: operations["ListBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List closed-game results. */
        get: operations["ListGameResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List games. */
        get: operations["ListGames"];
        put?: never;
        /** Create a game. */
        post: operations["CreateGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a game. */
        get: operations["GetGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/buy-ins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a buy-in to a game. */
        post: operations["AddBuyIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/cash-outs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a cash-out to a game. */
        post: operations["AddCashOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a game. */
        post: operations["CloseGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payments. */
        get: operations["ListPayments"];
        put?: never;
        /** Create a payment. */
        post: operations["CreatePayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a payment. */
        get: operations["GetPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List players. */
        get: operations["ListPlayers"];
        put?: never;
        /** Create a player. */
        post: operations["CreatePlayer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a player. */
        get: operations["GetPlayer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{id}/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Rename a player. */
        put: operations["RenamePlayer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a player. */
        post: operations["ArchivePlayer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddBuyInErrorResponse: {
            error: string;
        };
        AddBuyInRequest: {
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
        };
        AddBuyInResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            gameId: string;
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
            type: string;
            /** Format: date-time */
            recordedAtUtc: string;
        };
        AddCashOutErrorResponse: {
            error: string;
        };
        AddCashOutRequest: {
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
        };
        AddCashOutResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            gameId: string;
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
            type: string;
            /** Format: date-time */
            recordedAtUtc: string;
        };
        ArchivePlayerErrorResponse: {
            error: string;
        };
        ArchivePlayerResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            isActive: boolean;
        };
        CloseGameErrorResponse: {
            error: string;
        };
        CloseGameResponse: {
            /** Format: uuid */
            id: string;
            status: string;
            /** Format: date-time */
            createdAtUtc: string;
        };
        CreateGameResponse: {
            /** Format: uuid */
            id: string;
            status: string;
            /** Format: date-time */
            createdAtUtc: string;
        };
        CreatePaymentErrorResponse: {
            error: string;
        };
        CreatePaymentRequest: {
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
            type: string;
        };
        CreatePaymentResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
            type: string;
            /** Format: date-time */
            recordedAtUtc: string;
        };
        CreatePlayerErrorResponse: {
            error: string;
        };
        CreatePlayerRequest: {
            name: null | string;
        };
        CreatePlayerResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            isActive: boolean;
        };
        GetGameEntryResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
            type: string;
            /** Format: date-time */
            recordedAtUtc: string;
        };
        GetGameErrorResponse: {
            error: string;
        };
        GetGameResponse: {
            /** Format: uuid */
            id: string;
            status: string;
            /** Format: date-time */
            createdAtUtc: string;
            /** Format: double */
            totalBuyInAmount: number | string;
            /** Format: double */
            totalCashOutAmount: number | string;
            /** Format: double */
            remainingCashOutAmount: number | string;
            entries: components["schemas"]["GetGameEntryResponse"][];
        };
        GetPaymentErrorResponse: {
            error: string;
        };
        GetPaymentResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
            type: string;
            /** Format: date-time */
            recordedAtUtc: string;
        };
        GetPlayerErrorResponse: {
            error: string;
        };
        GetPlayerResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            isActive: boolean;
        };
        ListBalancesResponse: {
            /** Format: uuid */
            playerId: string;
            playerName: string;
            isActive: boolean;
            /** Format: double */
            gameNetAmount: number | string;
            /** Format: double */
            paymentNetAmount: number | string;
            /** Format: double */
            balanceAmount: number | string;
        };
        ListGameResultsResponse: {
            /** Format: uuid */
            playerId: string;
            playerName: string;
            /** Format: uuid */
            gameId: string;
            /** Format: date-time */
            playedAtUtc: string;
            /** Format: double */
            buyInAmount: number | string;
            /** Format: double */
            cashOutAmount: number | string;
            /** Format: double */
            netAmount: number | string;
        };
        ListGamesResponse: {
            /** Format: uuid */
            id: string;
            status: string;
            /** Format: date-time */
            createdAtUtc: string;
        };
        ListPaymentsResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            playerId: string;
            /** Format: double */
            amount: number | string;
            type: string;
            /** Format: date-time */
            recordedAtUtc: string;
        };
        ListPlayersResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            isActive: boolean;
        };
        RenamePlayerErrorResponse: {
            error: string;
        };
        RenamePlayerRequest: {
            name: null | string;
        };
        RenamePlayerResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            isActive: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListBalances: {
        parameters: {
            query?: {
                playerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBalancesResponse"][];
                };
            };
        };
    };
    ListGameResults: {
        parameters: {
            query?: {
                playerId?: string;
                gameId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListGameResultsResponse"][];
                };
            };
        };
    };
    ListGames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListGamesResponse"][];
                };
            };
        };
    };
    CreateGame: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateGameResponse"];
                };
            };
        };
    };
    GetGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetGameResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetGameErrorResponse"];
                };
            };
        };
    };
    AddBuyIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddBuyInRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddBuyInResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddBuyInErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddBuyInErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddBuyInErrorResponse"];
                };
            };
        };
    };
    AddCashOut: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCashOutRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddCashOutResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddCashOutErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddCashOutErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddCashOutErrorResponse"];
                };
            };
        };
    };
    CloseGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloseGameResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloseGameErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloseGameErrorResponse"];
                };
            };
        };
    };
    ListPayments: {
        parameters: {
            query?: {
                playerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPaymentsResponse"][];
                };
            };
        };
    };
    CreatePayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaymentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePaymentResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePaymentErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePaymentErrorResponse"];
                };
            };
        };
    };
    GetPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPaymentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPaymentErrorResponse"];
                };
            };
        };
    };
    ListPlayers: {
        parameters: {
            query?: {
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPlayersResponse"][];
                };
            };
        };
    };
    CreatePlayer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlayerRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePlayerResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePlayerErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePlayerErrorResponse"];
                };
            };
        };
    };
    GetPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPlayerResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPlayerErrorResponse"];
                };
            };
        };
    };
    RenamePlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenamePlayerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenamePlayerResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenamePlayerErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenamePlayerErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenamePlayerErrorResponse"];
                };
            };
        };
    };
    ArchivePlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchivePlayerResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchivePlayerErrorResponse"];
                };
            };
        };
    };
}
